[package]
name = "sherlog"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
crossterm = "0.26.0"
regex = "1.7.1"
tui = "0.19.0"

[dev-dependencies]
criterion = "0.4"

[lib]
bench = false

[[bench]]
name = "core"
harness = false