name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
        timeout-minutes: 5
      - name: Clippy
        run: cargo clippy
      - name: Format
        run: cargo fmt --check
